baseURL = "https://yodalee.me/"

languageCode = "en"
defaultLanguageCode = "en-us"

title = "Yodalee Note"

theme = "silhouette-hugo"

copyright = "Yodalee - All rights reserved."

paginate = 10
paginatePath = "page"

googleAnalytics = "UA-77945119-5"

[permalinks]
posts = "/:year/:month/:filename/"

[Params]
  Author = "YodaLee"
  IntroDescription = "My lifes, My notes"

# Define all supported taxonomies (add series to the default)
[taxonomies]
tags = "tags"
categories = "categories"
series = "series"

[Social]
  linkedin = "yodalee"
  github = "yodalee"
  email = "lc85301@gmail.com"
